### PR TITLE
Add easy deployment in gh-pages branch

### PR DESCRIPTION
**Pull request by Rub21**
@danielfdsilva  I have been using [gh-pages](https://www.npmjs.com/package/gh-pages) module to put the build files  production, I have added it in:

- https://github.com/developmentseed/geokit-doc-seed/blob/develop/package.json#L24
- https://github.com/developmentseed/sez-viewer/blob/master/package.json#L29

would be good to have it in doc-seed.

### CODE REVIEW

**Comment by danielfdsilva** [comment]
This is interesting.
We normally use continuous integration (Circle CI) to do the deployments. This allows for manual deployment quite easily, but since it is a very destructive operation, should it be this easy?

**Comment by Rub21** [comment]
@danielfdsilva , I did not know that we are using CI also I have not found the keys to configure it,  😬 ,  for the above repo we don't have the ci configuration and I thought using gh-pages it would be much easy to put in gh-pages. also would be good if we can add somethign about the CI in the documentation.

**Comment by danielfdsilva** [comment]
@Rub21 We usually set up the configuration once we clone the repo. Maybe would be good to include it here.

Here's an example of this being done: https://github.com/WorldBank-Transport/ram/blob/master/.circleci/config.yml

And here's a devlog on how to setup circle ci. https://github.com/developmentseed/how/issues/149

**Comment by Rub21** [comment]
sounds good,  closing this in favor of: https://github.com/developmentseed/doc-seed/pull/43

**Pull request closed without merging**
